
import ThemeRegistry from './ThemeRegistry'
import NavBar from './Components/NavBar';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  const { children } = props;
  
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <NavBar />
          {children}
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
