
import ThemeRegistry from './ThemeRegistry'
import NavBar from './Components/NavBar';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  const { children } = props;
  
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <NavBar />
          {children}
          </ThemeRegistry>
      </body>
    </html>
  );
}
